FROM nginx:alpine

# Clean up the default site config and files.
RUN rm /etc/nginx/conf.d/* && \
  rm /usr/share/nginx/html/*

# Install our own site config and files.
COPY config/nginx/conf.d /etc/nginx/conf.d
COPY app/public/ /usr/share/nginx/html
